apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-test-pod
  labels:
    app: spring-boot-test-app
spec:
  containers:
    - name: spring-boot-container
      image: spring_boot
      imagePullPolicy: Never
      ports:
      - containerPort: 8080