apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-boot-test-rc
spec:
  replicas: 3
  selector:
    app: spring-boot-test
  template:
    metadata:
      name: spring-boot-test-template
      labels:
        app: spring-boot-test
    spec:
      containers:
        - name: spring-boot-container
          image: spring_boot
          imagePullPolicy: Never
          ports:
            - containerPort: 8080